DROP TABLE IF EXISTS "AUTHORS";
CREATE TABLE IF NOT EXISTS "AUTHORS" (
  AUTHOR_ID         INTEGER PRIMARY KEY UNIQUE,
  NAME              VARCHAR(40) NOT NULL,
  SLUG              VARCHAR(40),
  IMAGE             VARCHAR(40),
  COVER             VARCHAR(100),
  BIO               VARCHAR(255),
  WEBSITE           VARCHAR(100),
  LOCATION          VARCHAR(40),
  ACCESSIBILITY     VARCHAR(40),
  STATUS            VARCHAR(40),
  LANGUAGE          VARCHAR(40),
  META_TITLE        VARCHAR(40),
  META_DESCRIPTION  VARCHAR(255),
  TOUR              VARCHAR(40),
  LAST_LOGIN        DATE,
  CREATED_AT        DATE,
  CREATED_BY        VARCHAR(40),
  UPDATED_AT        DATE,
  UPDATED_BY        VARCHAR(40)
);