DROP TABLE IF EXISTS "AUTHORS";
CREATE TABLE IF NOT EXISTS "AUTHORS" (
  AUTHOR_ID         INTEGER PRIMARY KEY UNIQUE,
  NAME              VARCHAR(40) NOT NULL,
  SLUG              VARCHAR(40),
  IMAGE             VARCHAR(40),
  COVER             VARCHAR(100),
  BIO               VARCHAR(255),
  WEBSITE           VARCHAR(100),
  LOCATION          VARCHAR(40),
  ACCESSIBILITY     VARCHAR(40),
  STATUS            VARCHAR(40),
  LANGUAGE          VARCHAR(40),
  META_TITLE        VARCHAR(40),
  META_DESCRIPTION  VARCHAR(255),
  TOUR              VARCHAR(40),
  LAST_LOGIN        DATE,
  CREATED_AT        DATE,
  CREATED_BY        VARCHAR(40),
  UPDATED_AT        DATE,
  UPDATED_BY        VARCHAR(40)
);

DROP TABLE IF EXISTS "POSTS";
CREATE TABLE IF NOT EXISTS "POSTS" (
  POST_ID           INTEGER PRIMARY KEY UNIQUE,
  TITLE             VARCHAR(40) NOT NULL ,
  SLUG              VARCHAR(40),
  MARKDOWN          VARCHAR(255),
  HTML              VARCHAR(255),
  IMAGE             VARCHAR(40),
  FEAUTURED         BOOLEAN,
  PAGE              BOOLEAN,
  STATUS            VARCHAR(40),
  LANGUAGE          VARCHAR(40),
  META_TITLE        VARCHAR(40),
  META_DESCRIPTION  VARCHAR(255),
  AUTHOR_ID         INTEGER REFERENCES "AUTHORS" (AUTHOR_ID),
  CREATED_AT        DATE,
  UPDATED_AT        DATE,
  PUBLISHED_AT      DATE,
  URL               VARCHAR(40),
  TAGS              TEXT[][]
);